version: '3.3'
networks:
  back-tier: null
services:
  besu:
    ports:
      - '8545:8545'
      - '30303:30303'
      - '9545:9545'
    image: 'hyperledger/besu:24.1.2'
    volumes:
      - '<PATH TO STORE YOUR CHAIN INFO>:/var/lib/besu/'
    environment:
      - BESU_NETWORK=classic
      - BESU_DATA_PATH=/var/lib/besu/
      - BESU_MAX_PEERS=16
      - BESU_METRICS_ENABLED=true
      - BESU_METRICS_HOST=0.0.0.0
      - BESU_METRICS_PORT=9545
      - BESU_RPC_HTTP_ENABLED=true
      - BESU_HOST_ALLOWLIST=*
      - BESU_RPC_HTTP_HOST=0.0.0.0
      - BESU_RPC_HTTP_PORT=8545
      - BESU_RPC_HTTP_CORS_ORIGINS=https://explorer-expedition.etc-network.info,https://chainlist.org,https://explorer-alethio.etc-network.info,https://explorer-blockscout.etc-network.info
      - BESU_RPC_HTTP_API=ETH,NET,WEB3,ADMIN
      - BESU_RPC_HTTP_AUTHENTICATION_ENABLED=false
      - BESU_RPC_WS_ENABLED=true
      - BESU_RPC_WS_API=ETH,NET,WEB3
      - BESU_RPC_WS_PORT=6174      
  prometheus:
    image: 'prom/prometheus:v2.48.1'
    volumes:
      - './prometheus/:/etc/prometheus/'
      - 'prometheus_data:/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
    networks:
      - back-tier
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: '10'
    
  grafana:
    image: grafana/grafana:10.2.3
    user: '472'
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=<ADMIN PASSWORD>
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - './grafana.ini:/etc/grafana/grafana.ini'
      - 'grafana_data:/var/lib/grafana'
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: '10'

  geth:
    image: etclabscore/core-geth:latest
    command: --classic  --syncmode full --gcmode archive --txlookuplimit=0 --http --http.port 8454 --http.addr 0.0.0.0 --http.api personal,eth,net,web3,txpool,trace,debug,admin --http.corsdomain "https://explorer-expedition.etc-network.info,https://chainlist.org,https://explorer-alethio.etc-network.info,https://explorer-blockscout.etc-network.info,https://multisig.etccooperative.org,https://multisig.dev.etccooperative.org" --http.vhosts "*"  --maxpeers 16
#    command: db stats --classic
#    command: --classic --vmodule 'rpc=5' debug RPC
    volumes:
      - '/mnt/tank/geth/classic:/root/.ethereum'
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 2000k
        max-file: '10' 
    
volumes:
  prometheus_data: {}
  grafana_data: {}
  pgdata: {}

